### ISSUE TITLE
Adding Extension Keyboard Shortcuts - Enhancement Suggestion

### ISSUE THREAD

**Issue by Cr8zyIvan** [ndsvw/Published-Date#5]
I don't know how much the Extension has evolved recently, but I have to say, I have been impressed with the results Published Date has been giving! Good job!

Also, I would so love to be able to activate the Extension with a Keyboard Shortcut!

Cheers!

**Comment by ndsvw** [comment]
Thank you very much.

> Also, I would so love to be able to activate the Extension with a Keyboard Shortcut!
Ok, no problem. I'm going to implement this.

In case you want to change the shortcut later: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

**Comment by ndsvw** [comment]
Alt+Shift+P btw

**Comment by Cr8zyIvan** [comment]
Works Perfectly. Thank you!
